[package]
authors = ["o2sh <ossama-hjaji@live.fr>"]
edition = "2018"
name = "provok"
version = "0.1.0"

[dependencies]
allsorts = {git = "https://github.com/yeslogic/allsorts.git", rev = "3947164a201ab5e15d5f23204faaaaaad52531aa"}
clap = "2.33.3"
euclid = "0.22.2"
failure = "0.1.8"
freetype = "0.7.0"
glium = "0.29.0"
harfbuzz-sys = "0.5.0"
lazy_static = "1.4.0"
line_drawing = "0.8.0"
lingua = "1.2.0"
log = "0.4.14"
ordered-float = "2.1.1"
palette = "0.5.0"
resize = "0.7.2"
rgb = "0.8.25"
serde = {version = "1.0.125", features = ["derive"]}
serde_json = "1.0.64"
smallvec = "1.6.1"
tinyvec = "1.2.0"
unicode-general-category = "0.4.0"
unicode-segmentation = "1.7.1"
unicode-width = "0.1.8"
xi-unicode = "0.3.0"
