[package]
authors = ["o2sh <ossama-hjaji@live.fr>"]
edition = "2018"
name = "provok"
version = "0.1.0"

[dependencies]
clap = "2.33.3"
euclid = "0.22.2"
failure = "0.1.8"
freetype = "0.7.0"
glium = "0.29.0"
harfbuzz-sys = "0.5.0"
lazy_static = "1.4.0"
line_drawing = "0.8.0"
log = "0.4.14"
palette = "0.5.0"
resize = "0.7.2"
rgb = "0.8.25"
serde = {version = "1.0.125", features = ["derive"]}
serde_json = "1.0.64"
smallvec = "1.6.1"
unicode-segmentation = "1.7.1"
unicode-width = "0.1.8"
xi-unicode = "0.3.0"

[target.'cfg(not(target_os = "macos"))'.dependencies]
servo-fontconfig = "0.5.1"

[target.'cfg(target_os="macos")'.dependencies]
font-loader = "0.11.0"
